#/*
#* Copyright (c) 2022 Gouvernement du Québec
#* Auteur: Philippe Foucault
#* SPDX-License-Identifier: LiLiQ-R-v.1.1
#* License-Filename: /LICENSE
#*/
##############################################################
# Requetes http pour l'émeteur d'attestations d'accès virtuel
##############################################################
# Avant usage, il faut renseigner les champs X-API-Key des 
# endpoints qui seront utilisés. 
# 
### Définition des variables globales 
@hostname = https://exp-port-e-admin.apps.exp.openshift.cqen.ca

####
#### Récupère list de connections pour cet agent
#### 
GET {{hostname}}/connections HTTP/1.1
X-API-Key: 
Content-Type: application/json


####
#### Récupère les schémas crées par cet agent
####
GET {{hostname}}/schemas/created HTTP/1.1
X-API-Key: 
Content-Type: : application/json"


####
#### Créer un schéma de droit d'accès virtuel du CQEN
####
POST {{hostname}}/schemas HTTP/1.1
X-API-Key: 
Content-Type: application/json

{
    "schema_name": "CQENDroitAccesVirtuel",
    "schema_version": "0.1",
    "attributes": [
        "email", 
        "time"
    ]
}

#### 1678
              
@schema_id = FUKLxsjrYSHgScLbHuPTo4:2:CQENDroitAccesVirtuel:0.1
@cred_def_id = FUKLxsjrYSHgScLbHuPTo4:3:CL:29366:RegistreAccesVirtuelCQEN

####
#### Crée la définition d'une attestation (CRED_DEF) du registre de droits d'accès du CQEN
####
POST {{hostname}}/credential-definitions HTTP/1.1
Content-Type: application/json
X-API-Key: 

{
  "support_revocation": true,
  "tag": "RegistreAccesVirtuelCQEN",
  "schema_id": "FUKLxsjrYSHgScLbHuPTo4:2:CQENDroitAccesVirtuel:0.1"
}


####
#### Récupère un schéma selon son {schema_id}
####
GET {{hostname}}/schemas/{{schema_id}} HTTP/1.1
X-API-Key: 
Content-Type: : application/json"


####
#### Récupère une attestation selon son {cred_def}
####
GET {{hostname}}/credential/{{cred_def_id}} HTTP/1.1
X-API-Key: 
Content-Type: : application/json"
