kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${NAME}-build-template
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${GRP_APPLICATION}
        app.kubernetes.io/part-of: ${GRP_APPLICATION}
        app-group: port-e
        role: build
        env: dev
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${GRP_APPLICATION}
        app.kubernetes.io/part-of: ${GRP_APPLICATION}
        app-group: port-e
        role: build
        env: dev
    spec:
      triggers:
        - type: ImageChange
        - type: ConfigChange
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: ${GIT_REPO_URL}
          ref: ${GIT_REF}
        contextDir: ${SOURCE_CONTEXT_DIR}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ${SOURCE_IMAGE_KIND}
            name: ${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${OUTPUT_IMAGE_TAG}
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the resources defined in this template.
    required: true
    value: email-verification-service
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together.
    required: true
    value: email-verification-service
  - name: ENV_NAME
    displayName: Environment Name
    description: Environment name.  For the build environment this will typically be 'tools'
    required: true
    value: tools
  - name: GRP_APPLICATION
    displayName: App Group
    description: Used to group components together.
    required: true
    value: ' '
  - name: GIT_REPO_URL
    displayName: Git Repo URL
    description: The URL to your GIT repo.
    required: true
    value: https://github.com/torjc01/indy-email-debug.git
  - name: GIT_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
    value: debug
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: false
    value: src
  - name: SOURCE_IMAGE_KIND
    displayName: Source Image Kind
    description: The 'kind' (type) of the  source image; typically ImageStreamTag,
      or DockerImage.
    required: true
    value: DockerImage
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    description: The name of the source image.
    required: true
    value: registry.access.redhat.com/rhscl/python-36-rhel7
  - name: SOURCE_IMAGE_TAG
    displayName: Source Image Tag
    description: The tag of the source image.
    required: true
    value: latest
  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
    value: latest
