# To clean up as much as possible excluding components that are in use, run this command:
# docker system prune -a
# docker volume prune
version: '3.8'
services:
  database:
    image: postgres:14.6-alpine
    environment:
      POSTGRES_DB: auth_e
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5533:5432
    networks:
      default:
        aliases:
          - "postgres.localhost"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    container_name: auth-e-api
    image: nestjs-api:1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3301:3300
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=auth_e
      - PORT=3300
      - MODE=DEV
      - RUN_MIGRATIONS=false
      - KEYCLOAK_URL=http://keycloak.localhost:8080
      - KEYCLOAK_REALM=Auth-E
      - KEYCLOAK_CLIENT_ID=angular-app
  frontend:
    container_name: auth-e-ui
    image: angular:1.0.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4301:80
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - api
    environment: 
      - KEYCLOAK_URL=http://keycloak.localhost:8080
      - KEYCLOAK_REALM=Auth-E
      - KEYCLOAK_CLIENT_ID=angular-app
  pgadmin-compose:
    container_name: auth-e-pgadmin
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@dev.com"
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports: 
      - "5300:80"
    depends_on: 
      - database    
  keycloak:
    image: quay.io/keycloak/keycloak:20.0
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: database
      DB_DATABASE: auth_e
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      JAVA_OPTS: -Dkeycloak.profile=preview -Dkeycloak.import=/opt/jboss/keycloak/imports/auth-e-realm.json
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: DEBUG
    volumes:
      - ./keycloak:/opt/jboss/keycloak/imports
    command:
      - start-dev
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      default:
        aliases:
          - "keycloak.localhost"
    depends_on:
      - database
volumes:
  postgres_data: