######################################################################
# oc process -f ./auth-e.yaml --param-file=./auth-e.dev.params | oc apply -f -
######################################################################
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${APP_NAME}
  annotations:
    description: Application qui démontre l'authentification par attestations d'identité numérique basé sur Hyperledger Aries et Hyperledger Indy.
    tags: CQEN, Hyperledger, ARIES, Indy, Angular, NestJS, PostgreSql
objects:
######################################################################
# PostgreSql Database
######################################################################
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: ${POSTGRESQL_NAME}
  spec:
    storageClassName: ${STORAGE_CLASS_NAME}
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${POSTGRESQL_VOLUME_SIZE}
- kind: Secret
  apiVersion: v1
  metadata:
    name: ${POSTGRESQL_NAME}
    annotations:
      template.openshift.io/expose-database-user: "{.data['database-user']}"
      template.openshift.io/expose-database-password: "{.data['database-password']}"
      template.openshift.io/expose-database-admin-user: "{.data['database-admin-user']}"
      template.openshift.io/expose-database-admin-password: "{.data['database-admin-password']}"
      template.openshift.io/expose-database-name: "{.data['database-name']}"
      template.openshift.io/expose-admin-api-key: "{.data['admin-api-key']}"
  stringData:
    database-user: "${POSTGRESQL_USERNAME}"
    database-password: "${POSTGRESQL_PASSWORD}"
    database-admin-user: "${POSTGRESQL_ADMIN_USERNAME}"
    database-admin-password: "${POSTGRESQL_ADMIN_PASSWORD}"
    database-name: "${POSTGRESQL_DATABASE_NAME}"
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${POSTGRESQL_NAME}
    annotations:
      template.alpha.openshift.io/wait-for-ready: 'true'
    labels:
      app: ${POSTGRESQL_NAME}
      app.kubernetes.io/part-of: auth-e
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${POSTGRESQL_NAME}
        from:
          kind: ImageStreamTag
          name: postgresql:latest
          namespace: openshift
        lastTriggeredImage: ''
    - type: ConfigChange
    replicas: 1
    selector:
      name: ${POSTGRESQL_NAME}
    template:
      metadata:
        labels:
          name: ${POSTGRESQL_NAME}
      spec:
        containers:
        - name: ${POSTGRESQL_NAME}
          image: " "
          ports:
          - containerPort: ${{POSTGRESQL_PORT}}
            protocol: TCP
          env:
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: ${POSTGRESQL_NAME}
                key: database-user
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${POSTGRESQL_NAME}
                key: database-password
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: ${POSTGRESQL_NAME}
                key: database-name
          - name: POSTGRESQL_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${POSTGRESQL_NAME}
                key: database-admin-password                
          resources:
            limits:
              memory: 512Mi
          volumeMounts:
          - name: ${POSTGRESQL_NAME}-data
            mountPath: "/var/lib/pgsql/data"
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: IfNotPresent
          capabilities: {}
          securityContext:
            capabilities: {}
            privileged: false
        volumes:
        - name: ${POSTGRESQL_NAME}-data
          persistentVolumeClaim:
            claimName: ${POSTGRESQL_NAME}
        restartPolicy: Always
        dnsPolicy: ClusterFirst
  status: {}
- kind: Service
  apiVersion: v1
  metadata:
    name: ${POSTGRESQL_NAME}
  spec:
    ports:
    - name: ${POSTGRESQL_NAME}
      protocol: TCP
      port: ${{POSTGRESQL_PORT}}
      targetPort: ${{POSTGRESQL_PORT}}
      nodePort: 0
    selector:
      name: ${POSTGRESQL_NAME}
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer: {}
######################################################################
# NestJS Backend
######################################################################
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${NESTJS_NAME}
- kind: BuildConfig
  apiVersion: v1
  metadata:
    annotations:
      app.openshift.io/vcs-uri: ${GITHUB_REPOSITORY_URI}
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      app: ${NESTJS_NAME}
    name: ${NESTJS_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NESTJS_NAME}:latest
    source:
      contextDir: backend
      git:
        uri: ${GITHUB_REPOSITORY_URI}
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
      type: Docker
    triggers:
      - type: ConfigChange
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${NESTJS_NAME}
    labels:
      app: ${NESTJS_NAME}
      app.kubernetes.io/part-of: auth-e
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - github:
          secretReference:
            name: auth-e-build
        type: GitHub
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - ${NESTJS_NAME}
          from:
            kind: ImageStreamTag
            name: "${NESTJS_NAME}:latest"
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      app: ${NESTJS_NAME}
    template:
      metadata:
        labels:
          app: ${NESTJS_NAME}
      spec:
        containers:
        - env:
          - name: MODE
            value: DEV
          - name: PORT
            value: "3300"
          - name: POSTGRES_DATABASE
            valueFrom:
              secretKeyRef:
                name: ${POSTGRESQL_NAME}
                key: database-name
          - name: POSTGRES_HOST
            value: ${POSTGRESQL_NAME}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${POSTGRESQL_NAME}
                key: database-password
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: ${POSTGRESQL_NAME}
                key: database-user
          - name: RUN_MIGRATIONS
            value: "false"
          - name: KEYCLOAK_URL
            value: https://${KEYCLOAK_SUBDOMAIN}.${APP_DOMAIN}
          - name: KEYCLOAK_REALM
            value: ${KEYCLOAK_REALM}
          - name: KEYCLOAK_CLIENT_ID
            value: ${KEYCLOAK_CLIENT_ID}
          name: ${NESTJS_NAME}
          image: " "
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
        initContainers:
        - name: init-db
          image: busybox
          command: ['sh', '-c', 'until nc -z ${POSTGRESQL_NAME}:${POSTGRESQL_PORT}; do echo waiting for db; sleep 2; done;']
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
- kind: Service
  apiVersion: v1
  metadata:
    name: ${NESTJS_NAME}
  spec:
    selector:
      app: ${NESTJS_NAME}
    ports:
      - name: "3000"
        protocol: TCP
        port: 3000
        targetPort: 3000
######################################################################
# Angular Frontend
######################################################################
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: nginx.conf
  data:
    nginx.conf: "server {\n\t
                  listen ${NGINX_PORT} default_server;\n\n\t
                  client_max_body_size 100M;\n\t
                  charset utf-8;\n\n\t
                  location /api/v1 {\n\t\t
                    proxy_pass http://${NESTJS_NAME}:3000/api/v1;\n\t
                  }\n
                }"
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${ANGULAR_NAME}
- kind: BuildConfig
  apiVersion: v1
  metadata:
    annotations:
      app.openshift.io/vcs-uri: ${GITHUB_REPOSITORY_URI}
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      app: ${ANGULAR_NAME}
    name: ${ANGULAR_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${ANGULAR_NAME}:latest
    source:
      contextDir: frontend
      git:
        uri: ${GITHUB_REPOSITORY_URI}
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
      type: Docker
    triggers:
      - type: ConfigChange
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${ANGULAR_NAME}
    labels:
      app: ${ANGULAR_NAME}
      app.kubernetes.io/part-of: auth-e
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - ${ANGULAR_NAME}
          from:
            kind: ImageStreamTag
            name: "${ANGULAR_NAME}:latest"
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      app: ${ANGULAR_NAME}
    template:
      metadata:
        labels:
          app: ${ANGULAR_NAME}
      spec:
        containers:
          - name: ${ANGULAR_NAME}
            image: " "
            ports:
              - containerPort: ${{NGINX_PORT}}
                protocol: TCP
            env:
            - name: KEYCLOAK_URL
              value: https://${KEYCLOAK_SUBDOMAIN}.${APP_DOMAIN}
            - name: KEYCLOAK_REALM
              value: ${KEYCLOAK_REALM}
            - name: KEYCLOAK_CLIENT_ID
              value: ${KEYCLOAK_CLIENT_ID}
            resources: {}
            volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-conf-claim
            - mountPath: /var/cache/nginx/client_temp
              name: nginx-temp
            - mountPath: /var/cache/nginx/proxy_temp
              name: nginx-temp
            - mountPath: /var/cache/nginx/fastcgi_temp
              name: nginx-temp
            - mountPath: /var/cache/nginx/scgi_temp
              name: nginx-temp
            - mountPath: /var/cache/nginx/uwsgi_temp
              name: nginx-temp
            - mountPath: /var/run/
              name: nginx-run
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: Always
        initContainers:
        - name: init-db
          image: busybox
          command: ['sh', '-c', 'until nc -z ${POSTGRESQL_NAME}:${POSTGRESQL_PORT}; do echo waiting for db; sleep 2; done;']
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
        volumes:
        - name: nginx-conf-claim
          configMap:
            name: nginx.conf
        - name: nginx-temp
          emptyDir: { }
        - name: nginx-run
          emptyDir: { }
- kind: Service
  apiVersion: v1
  metadata:
    name: ${ANGULAR_NAME}
  spec:
    selector:
      app: ${ANGULAR_NAME}
    ports:
      - name: "10000"
        protocol: TCP
        port: 10000
        targetPort: ${{NGINX_PORT}}
- kind: Route
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
  spec:
    host: ${APP_SUBDOMAIN}.${APP_DOMAIN}
    to:
      kind: Service
      name: ${ANGULAR_NAME}
      weight: 100
    port:
      targetPort: 10000
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: None
    wildcardPolicy: None
  status:
    ingress:
      - host: ${APP_SUBDOMAIN}.${APP_DOMAIN}
        routerName: default
        conditions:
          - type: Admitted
            status: "True"
        wildcardPolicy: None
        routerCanonicalHostname: ${APP_DOMAIN}

######################################################################
# Parameters
######################################################################
parameters:
- name: APP_NAME
  displayName: Application name
  description: Used to group components together in the OpenShift console.
  required: true
  value: "auth-e"
- name: APP_DOMAIN
  description: The external hostname to access the application.
  required: true
- name: APP_SUBDOMAIN
  description: The external subdomain to access the application.
  required: true
  value: "auth-e"
- name: KEYCLOAK_SUBDOMAIN
  description: The external subdomain to access the application.
  required: true
  value: "auth-e-keycloak"
- name: POSTGRESQL_USERNAME
  displayName: PostgreSQL connection username
  description: Username for the PostgreSQL connection user.
  required: true
  value: "dbuser"
- name: POSTGRESQL_PASSWORD
  displayName: PostgreSQL connection password
  description: Password for the PostgreSQL connection user.
  required: true
  generate: "expression"
  from: "[a-zA-Z0-9]{16}"
- name: POSTGRESQL_ADMIN_USERNAME
  fdisplayName: PostgreSQL administrator username
  description: Username for the PostgreSQL administrative account.
  required: true
  value: "postgres"  
- name: POSTGRESQL_ADMIN_PASSWORD
  fdisplayName: PostgreSQL administrator password
  description: Password for the PostgreSQL administrative account.
  required: true
  generate: "expression"
  from: "[a-zA-Z0-9]{16}"
- name: POSTGRESQL_DATABASE_NAME
  displayName: PostgreSQL database name
  description: Name of the PostgreSQL database.
  required: true
  value: "auth_e"
- name: POSTGRESQL_PORT
  displayName: PostgreSQL database port
  description: Port on which PostgreSQL listens.
  required: true
  value: "5432"
- name: NGINX_PORT
  displayName: NGINX port
  description: Port on which nginx listens.
  required: true
  value: "8080"
- name: POSTGRESQL_NAME
  displayName: PostgreSQL name
  description: The name assigned to all PostgreSQL objects defined in this template.
  required: true
  value: "postgres-database"
- name: STORAGE_CLASS_NAME
  displayNgp2iption: The storage class of the volume.
  required: true
  value: gp2
- name: POSTGRESQL_VOLUME_SIZE
  displayName: PostgreSql volume size
  description: The size of the PostgreSql persistent volume, e.g. 512Mi, 1Gi, 2Gi.
  required: true
  value: 1Gi
- name: NESTJS_NAME
  displayName: NestJS name
  description: The name assigned to all NestJS objects defined in this template.
  required: true
  value: "nestjs-auth-e-backend"
- name: ANGULAR_NAME
  displayName: Angular name
  description: The name assigned to all Angular objects defined in this template.
  required: true
  value: "angular-frontend"
- name: GITHUB_REPOSITORY_URI
  displayName: GitHub repository URI
  description: URI of the GitHub repository.
  required: true
  value: "https://github.com/foxbike/auth-e.git"
- name: KEYCLOAK_NAME
  displayName: Keycloak name
  description: The name assigned to all Keycloak objects defined in this template.
  required: true
  value: "auth-e-keycloak"
- name: KEYCLOAK_ADMIN_USER
  displayName: Keycloak administrator username
  description: Username for the Keycloak administrative account.
  required: true
  value: "admin"
- name: KEYCLOAK_ADMIN_PASSWORD
  displayName: Keycloak administrator password
  description: Password for the Keycloak administrative account.
  required: true
  generate: "expression"
  from: "[a-zA-Z0-9]{16}"
- name: KEYCLOAK_REALM
  displayName: Keycloak realm
  description: Keycloak realm.
  required: true
  value: "Auth-E"
- name: KEYCLOAK_CLIENT_ID
  displayName: Keycloak client id
  description: Keycloak client identifier.
  required: true
  value: "angular-app"
- name: KEYCLOAK_DATABASE_NAME
  displayName: Keycloak database name
  description: Name of the Keycloak database.
  required: true
  value: "keycloak"
