@startuml
!pragma revision 1

title
    Port-E
    Architecture technologique
    Expérimentation du portefeuille en tant qu'employé
end title

caption Diagramme d'architecteurs des composants par rapports aux différents acteurs

'********************
'DÉFINITION DES OBJETS DU DIAGRAMME
'********************
' Références graphique
' L'information se retrouve ici pour utiliser les icon AWS avec plant UML : https://github.com/awslabs/aws-icons-for-plantuml
' La liste de tous les icones disponibles sont référencés ici : https://github.com/awslabs/aws-icons-for-plantuml/blob/main/AWSSymbols.md
' Sinon tous les icones natifs de plantUML sont aussi utilisables.
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v14.0/dist
!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-2/dist

' Composants graphique
!include AWSPuml/AWSSimplified.puml
!includeurl AzurePuml/AzureSimplified.puml

!include AWSPuml/Analytics/CloudSearchSearchDocuments.puml
!include AWSPuml/ApplicationIntegration/ConsoleMobileApplication.puml
!include AWSPuml/General/Mobileclient.puml
!include AWSPuml/Blockchain/Blockchain.puml
!include AWSPuml/BusinessApplications/SimpleEmailService.puml
!include AWSPuml/BusinessApplications/SimpleEmailServiceEmail.puml
!include AWSPuml/Containers/all.puml
!include AWSPuml/Database/all.puml
!include AWSPuml/General/all.puml
!include AWSPuml/General/GenericApplication.puml
'!include AWSPuml/Groups/all.puml
!include AWSPuml/InternetOfThings/IoTThingDoorLock.puml
!include AWSPuml/SecurityIdentityCompliance/Cognito.puml
!include AWSPuml/SecurityIdentityCompliance/IAMIdentityCenter.puml
!include AWSPuml/Storage/SimpleStorageServiceS3Standard.puml

!includeurl AzurePuml/Blockchain/AzureBlockchainConsortium.puml
!includeurl AzurePuml/Integration/AzureEventGrid.puml
!includeurl AzurePuml/Mobile/AzureMobileApp.puml
!includeurl AzurePuml/Networking/AzureFrontDoor.puml
!includeurl AzurePuml/Stack/AzureStackCapacity.puml
!includeurl AzurePuml/Web/AzureWebApp.puml
!includeurl AzurePuml/Web/AzureContainerSettings.puml

left to right direction
Users(dir, "Directeurs", "Approbation des accès")
Users(admin, "Administrateur(e)s CEAI", "Donneur d'accès")
Users(adj, "Adjoint(e)s", "Donneur d'accès")
Users(rep, "Représentant(e)s", "Donneur d'accès")
User(emp, "Employé(e)", "L'utilisateur")
AzureBlockchainConsortium(dltCANdy, "Chaîne de blocs\nCANdy", "Registre de confiance") #LightGreen


rectangle "GESTION DES ACCÈS" {
    rectangle "ATTRIBUTION D'ACCÈS" {
        package Authentifications as auth1 {
            rectangle "<$AzureFrontDoor>\nKeycloak Lab CEAI\nRealm Port-E" as UC0 #Yellow
        }

        package "Octroyer l'accès" {
            rectangle "<$AzureWebApp>\nSite Web\nGestion des accès\nInterface pour sélectionner les accès à octroyer" as webApp #Yellow
            note right of webApp #Yellow
                "TODO: permettre de sélectionner 3 types d'accès:\n
                1- l'accès CEAI - créer l'interface graphique équivalent au CLI
                2- l'accès physique - créer un Mock d'accès de porte: 
                    2.1- accès (A) au 1500 Cyrille-Duquet, 1er étage
                    2.2- accès (B) au 150 R-L Est, 10e étage
                3- BONUS, l'accès à taiga :
                    3.1- créer le Realm Keycloak taiga et interconnecter en OpenIDconnect
                    3.2- EN EXTRA, ajouter le MFA dans keycloak pour Taiga pour rencontrer la règle en cybersécurité
                        Mais exclure le vc-authn-oidc du MFA - considéré comme moyen équivalent du user/pwd + MFA
                4- SUPER BONUS, l'accès à Odoo
                    4.1- créer le Realm Keycloak Odoo et interconnecter en OpenIDconnect
                    4.2- EN EXTRA, ajouter le MFA dans keycloak pour Odoo pour rencontrer la règle en cybersécurité
                        Mais exclure le vc-authn-oidc du MFA - considéré comme moyen équivalent du user/pwd + MFA"
            end note 
    
            rectangle "<$AzureEventGrid>\nAPI consigner l'accès\nvirtuel et physique\n(NestJS)" as apiApp #Yellow
            note left of apiApp #Yellow: "TODO: consigner email vs accès virtuel \nET email vs accès physique"
        }

        package "Gestionnaire Accès" {
            rectangle "<$AzureEventGrid>\nAPI Centre d'expertise appliquée en innovation du CQEN (CEAI)" as ceai #LightGreen
            note right of ceai #Yellow: "TODO: Appeler l'API REST du CEAI"
            
            rectangle "<$AzureEventGrid>\nAPI Realm des outils de travail\n(Taiga et Odoo)" as apiOutils #Yellow
            note right of apiOutils #Yellow: "TODO: Créer un API REST\ncalquer sur celui du CEAI"

            rectangle "<$AzureEventGrid>\nAPI Accès physique" as physique #Yellow
            note right of physique #Yellow: "Simule l'appel de l'API du fournisseur\ndes accès physique des immeubles"
        }
    }

    rectangle "ÉMISSION ACCÈS" {
        package "Libre service de l'émission des accès" {
            
            rectangle "<$AzureContainerSettings>\nSite Web\nContrôleur Émetteur" as controllerIssuer #LightGreen
            note right of controllerIssuer #Yellow: "TODO: Ajouter le Out-of-band protocol\n afin de réutiliser la même connexion\n(requis pour le message)"
            database "$AuroraPostgreSQLInstanceIMG()\nDB Contrôleur" as dbC #LightGreen
            note left of dbC #Yellow: "TODO: valider la présence de email vs connexion"

            package "ACA-PY" as AgentI {
                rectangle "$ElasticContainerServiceContainer1IMG()\nAgent Émetteur" as agentIssuer #LightGreen
                database "$AuroraPostgreSQLInstanceIMG()\nAgent Wallet" as kmsIssuer #LightGreen
                rectangle "$ElasticContainerServiceContainer1IMG()\nTail" as tailServerIssuer #LightGreen
            }
            
            rectangle "<$AzureStackCapacity>\nBackup" as bk1 #Yellow
            note left of bk1 #Yellow: "TODO: Installer EFS comme type de volume sur la PDM CEAI\nDéployer conteneur de prise de backup des fichiers des BD"
            rectangle "$SimpleEmailServiceIMG()\nSMTP\nEnvoi de courriels" as smtp #LightGreen
        }
    }
}

rectangle "DÉTENTEUR D'ACCÈS" {
    rectangle "$MobileclientIMG()\nMobile" as cellEmp {
        rectangle "<$AzureMobileApp>\nPortefeuille numérique" as appEmp {
            rectangle "$CognitoIMG()\nAttestation vérifiable\ndu courriel" as vcEmail #LightGreen
            
            rectangle "$CloudSearchSearchDocumentsIMG()\nGestion du consentement\npour les demandes subséquentes" as vcConsent #Yellow
        }
        rectangle "$ConsoleMobileApplicationIMG()\nMagasins d'applications\n(TestFlight Apple)\nPipeline de déploiement automatisé" as appStore #LightGreen
        note right of appStore #Yellow: "TODO: Déployer sur PlayConsole pour Android\nCréer pipeline de déploiement automatisé Android"
    }

    package "ACA-PY" as AgentM {
        rectangle "$ElasticContainerServiceContainer1IMG()\nAgent Médiateur" as agentMediator #LightGreen
        database "$AuroraPostgreSQLInstanceIMG()\Agent Wallet" as kmsM #LightGreen
    }

    rectangle "$SimpleEmailServiceEmailIMG()\nBoîte de courriels" as boiteEmail #LightGreen
}

rectangle "UTILISATION D'ACCÈS" {
    package "Authentification aux outils de travail" as auth2 {
        package "Authentification" {
            rectangle "<$AzureFrontDoor>\nKeycloak Lab CEAI" as UC1 #Yellow
            rectangle "$IAMIdentityCenterIMG()\nOpenID Provider" as OIP #Yellow
            note right of OIP #Yellow: "Utiliser le endpoint pour configurer la proof request du email CQEN"
            package "ACA-PY" as AgentC1 {
                rectangle "$ElasticContainerServiceContainer1IMG()\nAgent consommateur virtuel" as agentConsumerV #Yellow
                database "$AuroraPostgreSQLInstanceIMG()\Agent Wallet" as kmsCV #Yellow
            }
        }

        package "Accès virtuel" {
            usecase "Lab CEAI" as UC2 #LightGreen
            note right of UC2 #Yellow: "Configurer le nouvelle Open ID Provider\nd'attestation vérifiable (vc-authn-oidc)"
            usecase "Kanban et Scrum\n(Taiga)" as UC3 #LightGreen
            note right of UC3 #Yellow: "Configurer OIDC"
            usecase "AWS CEAI" as UC5 #LightGreen
            usecase "OpenShift CEAI" as UC6 #LightGreen
            usecase "CodeReady CEAI" as UC7 #LightGreen
            usecase "Gestion clients CQEN\n(Odoo)" as UC8 #Yellow
            note right of UC8 #Yellow: "Configurer OIDC"
        }
    }

    package "Déverrouillage de portes d’accès sur les lieux de travail" as porte1 {
        package "Internet des objets - Lecteur NFC aux Portes" {
            rectangle "$IoTThingDoorLockIMG()\nPorte A\n1500 Cyrille-Duquet\n1er étage" as UC4 #Yellow
            rectangle "$IoTThingDoorLockIMG()\nPorte B\n150 René-Lévesque Est\n10e étage" as UC9 #Yellow
        }

        rectangle "<$AzureContainerSettings>\nSite Web\nContrôleur Émetteur" as controllerConsumerP #Yellow
        package "ACA-PY" as AgentC2 {
            rectangle "$ElasticContainerServiceContainer1IMG()\nAgent consommateur physique" as agentConsumerP #Yellow
            database "$AuroraPostgreSQLInstanceIMG()\Agent Wallet" as kmsCP #Yellow        
        }
    }
}

'********************
'DÉFINITION DES LIENS
'********************

'--------------------
'ATTRIBUTION D'ACCÈS
' Lien interne
UC0 --> webApp
webApp --> physique
webApp -down-> apiApp
webApp --> ceai
webApp --> apiOutils
' Lien externe
' Directeurs
dir --> adj
dir --> rep
dir --> admin
' Adjoint(e) 
adj --> UC0
' Représentant(e)
rep --> UC0
' Administrateur CEAI
admin --> UC0
' BD
apiApp --> dbC

'--------------------
'ÉMISSION ACCÈS
'Employé(e)
' Lien interne
controllerIssuer -down-> dbC
controllerIssuer -down-> agentIssuer
controllerIssuer --> smtp
agentIssuer -down-> kmsIssuer
agentIssuer --> tailServerIssuer 
bk1 --> dbC
bk1 --> kmsIssuer
' Lien externe
emp --> controllerIssuer
appEmp --> controllerIssuer
agentIssuer --> dltCANdy
smtp --> boiteEmail
emp --> boiteEmail
boiteEmail --> controllerIssuer

'--------------------
'DÉTENTEUR ACCÈS
'Employé(e)
' Lien interne
appEmp -down-> agentMediator
agentMediator -down-> kmsM
appStore --> appEmp
' Lien externe
emp --> appStore
emp --> appEmp
appEmp --> dltCANdy
agentMediator --> dltCANdy
agentMediator <--> agentIssuer

'--------------------
'UTILISATIONS ACCÈS
'Déverrouiller porte
' Lien interne
UC4 <--> controllerConsumerP
UC9 <--> controllerConsumerP
UC4 <-- agentConsumerP
UC9 <-- agentConsumerP
controllerConsumerP -down-> agentConsumerP
agentConsumerP -down-> kmsCP
' Lien externe
controllerConsumerP --> dbC
agentConsumerP <--> agentMediator
agentConsumerP --> dltCANdy
emp --> UC4
'cellEmp --> UC4
emp --> UC9
'cellEmp --> UC9

'Authentification virtuel
' Lien interne
UC1 <--> OIP
OIP <-down-> agentConsumerV
agentConsumerV -down-> kmsCV
'Accès virtuel
UC1 -right-> UC2
UC1 -right-> UC3
UC2 --> UC5
UC2 --> UC6
UC2 --> UC7
UC1 -right-> UC8
' Lien externe
agentConsumerV <--> agentMediator
agentConsumerV --> dltCANdy
emp --> UC1
'cellEmp --> UC1

@enduml