@startuml "port-e cas d'utilisations"
title
    Port-e
    Cas d'utilisations
    Expérimentation du portefeuille en tant qu'employé
end title

caption Diagramme de cas d'utilisations par rapports aux différents acteurs

'********************
'DÉFINITION DES OBJETS DU DIAGRAMME
'********************

'Références graphique
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/master/dist

'Composants graphique
!includeurl AWSPuml/AWSSimplified.puml
!includeurl AWSPuml/General/MobileClient.puml
!includeurl AWSPuml/Blockchain/Blockchain.puml

left to right direction
actor Directeurs as dir
actor "Adjoint(e)" as adj
actor "Représentant(e)" as rep

actor "Administrateur CEAI" as admin #LightGreen
actor "Employé(e)" as emp #LightGreen
component "$MobileclientIMG()" as cellCA #LightGreen
Blockchain(dltCA, "Blockchain CANdy", "BackEnd", "Registre de confiance") #LightGreen


rectangle "ATTRIBUTION D'ACCÈS" {
    package Authentifications as auth1 {
        usecase "Keycloak Lab CEAI" as UC0 
    }
    package "Gestionnaire Accès" {
        usecase "CEAI" as ceai #LightGreen
        usecase "Taiga" as taiga
        usecase "Ajouter Membre" as addtaiga
        usecase "Créer Membre" as createtaiga
        usecase "Accès physique" as physique
    }
}

rectangle "ENVOI DE MESSAGES" {
    package Notifications as notif {
        usecase "Notifier employés" as UC8 
    }
}


rectangle "ÉMISSION ACCÈS" {
    package "Libre service de l'émission des accès" {
        usecase "Saisir courriel" as email
        usecase "Recevoir courriel avec URL OTP" as opt
        usecase "Lecture code barre" as cab2d
        usecase "Réception attestation d'accès CQEN" as vc
    }
}

rectangle "UTILISATION ACCÈS" {
    package "Accès virtuel" {
        package Authentifications as auth2 {
            usecase "Keycloak Lab CEAI" as UC1 #Yellow
            APIGateway(virtualVerifierAgent, "Agent vérificateur virtuel", "BackEnd", "Consommateur CQEN vc-auth") #Yellow
        }
        usecase "Lab CEAI" as UC2 #LightGreen
        usecase "Taiga" as UC3
        usecase "AWS CEAI" as UC5 #LightGreen
        usecase "OpenShift CEAI" as UC6 #LightGreen
        usecase "CodeReady CEAI" as UC7 #LightGreen
    }
    package "Accès physique" {
        usecase "Fausse porte" as UC4
        component "Controlleur d'accès physique" as controller
        APIGateway(physicalVerifierAgent, "Agent vérificateur physique", "BackEnd", "Consommateur CQEN vc-auth") #LightGray
    }
}

'********************
'DÉFINITION DES LIENS
'********************

'ATTRIBUTION D'ACCÈS
'Directeurs
dir --> adj
dir --> rep
dir --> admin

'Adjoint(e) 
adj --> UC0
UC0 --> physique

'Représentant(e)
rep --> UC0
UC0 --> taiga
taiga --> addtaiga
taiga --> createtaiga

'Administrateur CEAI
admin --> UC0
UC0 --> ceai

'Notifier
admin --> UC8
rep --> UC8
adj --> UC8
UC8 --> issuerAgent
issuerAgent -left-> cellCA

'ÉMISSION ACCÈS
'Employé(e)
emp -right-> cellCA
emp --> email
email --> opt
opt --> cab2d
cellCA --> cab2d
cab2d --> vc 
'lien vers l'agent
opt -- issuerAgent
cab2d -- issuerAgent
vc -- issuerAgent

'UTILISATIONS ACCÈS
'Employé(e)
'accès virtuel
cellCA -right-> UC1
UC1 -left-> UC2
UC1 -left-> UC3
UC1 -- virtualVerifierAgent
virtualVerifierAgent -- cellCA
UC2 --> UC5
UC2 --> UC6
UC2 --> UC7

'accès physique
cellCA -right-> UC4
UC4 -- controller
controller -- physicalVerifierAgent
physicalVerifierAgent -left- cellCA

'LIEN VERS LA BLOCKCHAIN
cellCA -- dltCA
physicalVerifierAgent -- dltCA
issuerAgent -- dltCA
virtualVerifierAgent -- dltCA

@enduml