@startuml "Posseder l'accès"

'**************
'PROCESSUS DE VÉRIFICATION
'**************
caption "Posséder l'accès"
actor "Employé" as empl
actor "Administrateur d'accès" as admin
usecase "Donner accès" as donne
usecase "Télécharger App Porte:E" as app
usecase "Recevoir courriel de vérification" as verif
usecase "Lire code QR" as scan
usecase "Autodemander invitation" as autodemande

admin --> donne
donne -|> autodemande
empl --> app
empl --> autodemande
autodemande --> verif
verif --> scan
app --> fin
scan --> fin
@enduml