version: "3"

services:
  raccourci-db:
    container_name: ${APP}-postgresdb-${SUFFIX}
    image: postgres:15.1
    ports:
      - 35432:5432
    networks:
      - ${NETWORK}
    volumes:
      - ./data/postgres-data:/data/postgres
    restart: always
    env_file:
      - .env

  raccourci-api:
    container_name: ${APP}-api-${SUFFIX}
    image: raccourci-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    networks: 
      - ${NETWORK}
    restart: unless-stopped
    depends_on: 
      - raccourci-db

networks:
  raccourci-network: